version: '1'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://cluster22137.0deohmn.mongodb.net/petpaldb
      - MONGO_USER=${DATABASE_USERNAME}
      - MONGO_PASSWORD=yourMongoDBPassword=${DATABASE_PASSWORD}
