version: '3'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=development